SET SQL DIALECT 3;
SET NAMES UTF8;


CREATE DOMAIN D_BOOL AS SMALLINT CHECK (value in (0, 1));

CREATE DOMAIN D_TIME AS TIME;
CREATE DOMAIN D_TIMESTAMP AS TIMESTAMP;
CREATE DOMAIN D_DATE AS DATE;
CREATE DOMAIN D_DATETIME AS TIMESTAMP;

CREATE DOMAIN D_DOUBLE AS DOUBLE PRECISION;
CREATE DOMAIN D_FLOAT AS FLOAT;

CREATE DOMAIN D_ID AS BIGINT;
CREATE DOMAIN D_INTEGER AS INTEGER;

CREATE DOMAIN D_BLOB_TEXT AS BLOB SUB_TYPE 1 SEGMENT SIZE 80 COLLATE UNICODE_CI;
CREATE DOMAIN D_STR_20 AS VARCHAR(20) COLLATE UNICODE_CI;
CREATE DOMAIN D_STR_255 AS VARCHAR(255) COLLATE UNICODE_CI;
CREATE DOMAIN D_STR_8100 AS VARCHAR(8100) COLLATE UNICODE_CI;
CREATE DOMAIN D_STR_LONG AS VARCHAR(1024) COLLATE UNICODE_CI;